name = "PyQDecoders"
uuid = "17f5de1a-9b79-4409-a58d-4d45812840f7"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Conda = "1.10"
PyCall = "1.96"
julia = "1.9"
